### ISSUE TITLE
undefined reference to `shiftOutByte'

### ISSUE THREAD

**Issue by Nout1** [dalxo/nRF24L01_t13#2]
I'm trying to use this library in the arduino IDE but get an error

In function `nrf24_writeRegs':
nRF24L01_t13-main/nRF24L01.c: line 369: undefined reference to `shiftOutByte'

However when looking in nRF24L01.c the function does exit and seems to have the correct name
Any hints how I can solve this?

**Comment by dalxo** [comment]
This project as a whole was never intended for Arduino IDE (seriously for t13?) builds but for regular "plain" projects. Very likely you have issues with Arduino's IDE default settings of the toolchain, paths, etc. I suggest you use regular professional tools, e.g. Microchip Studio or similar for your ATtiny projects. 

Which version of Arduino IDE do you use and what is your target controller? I will have look if I can replicate your setup.

**Comment by Nout1** [comment]
I noticed that when calling this function outside of an assembler block it is recognized correctly while called from inside an assembler block it is not recognized?

Eg this works
uint8_t nrf24_readReg(uint8_t cmd) {
	NRF24L01_CSN_SET();		//
	NRF24L01_CSN_CLR();
	cmd = shiftOutByte(cmd);
	NRF24L01_CSN_SET();	
	NRF24L01_CSN_CLR();
	return cmd;
}

but this fails
void nrf24_writeReg(uint8_t cmd, uint8_t value) {
	NRF24L01_CSN_SET();
	NRF24L01_CSN_CLR();		
	asm volatile (
		"rcall shiftOutByte			\n\t"
		"mov	r24, r22			\n\t"
		"rcall shiftOutByte			\n\t"
		:: 
	);
	NRF24L01_CSN_SET();
	NRF24L01_CSN_CLR();
}

**Comment by Nout1** [comment]
I've been using arduino IDE multiple times with ATTINY13 (and 25 + 85 as well), without issues, but I did not use assembler yet

Find a very simple sketch that already shows the issue

#define F_CPU 1200000UL  //ONLY used if fuse was set to lower internal frequency
#include <avr/io.h>
#include <util/delay.h>
#include "projdefs.h"
#include <nRF24L01.h>

void setup() {
}

void loop() {
}

Arduino IDE version 1.8.13
Error message is on the picture
Setting are as follows
![image](https://user-images.githubusercontent.com/13803887/148662109-e14b547e-afca-4052-ae86-d61dad50bf4e.png)

**Comment by dalxo** [comment]
Seems like your compiler/linker cannot see that method. Try this (hints): 
1) Add declaration of that function into the header file, i.e. "uint8_t shiftOutByte(uint8_t data);"
2) If that still does not work, add to the declaration keyword "extern".

I purposefully did not include declaration in the header file to avoid users will call it directly from anywhere in the code - that method relies on some register usage and parameter passing which will not work correctly if used outside the nRF24L01.c. 

Anyway, I am going to have a look at it and will be back. Thanks for posting this issue, it has made me realize to put in the readme a list of supported toolchains.

**Comment by Nout1** [comment]
I've added the function to the header file => still fails
Also when adding extern it still fails

Is it essential to make the call in assembled?
```
void nrf24_writeReg(uint8_t cmd, uint8_t value) {
NRF24L01_CSN_SET();
NRF24L01_CSN_CLR();
asm volatile (
"rcall shiftOutByte \n\t"
"mov r24, r22 \n\t"
"rcall shiftOutByte \n\t"
::
);
NRF24L01_CSN_SET();
NRF24L01_CSN_CLR();
}
```

Or could I change it to 
```
void nrf24_writeReg(uint8_t cmd, uint8_t value) {
NRF24L01_CSN_SET();
NRF24L01_CSN_CLR();
cmd = shiftOutByte(cmd);
asm volatile (
"mov r24, r22 \n\t"
::          //I'm not sure what this line means?
);
cmd = shiftOutByte(cmd);
NRF24L01_CSN_SET();
NRF24L01_CSN_CLR();
}
```

**Comment by Nout1** [comment]
From the project description it looks like the schematics could have been drawn in EasyEDA and possibly a PCB was drawn as well? 
It this would be true, would you be willing to share it?
Not sure it would fit my needs, but might be a starting point

**Comment by dalxo** [comment]
Arduino compiles by default in CPP "mode", I think name mangling could be the problem. Try to wrap definition of the entire shiftOutByte in the C extern:

extern "C" {
  uint8_t shiftOutByte(uint8_t data) {
    ....
  }

}

**Comment by dalxo** [comment]
I can replicate the problem in the Arduino IDE 1.8.19. Will look at the fix tomorrow.  Btw, that "extern" didn't work.

**Comment by Nout1** [comment]
There are 3 functions that call the shiftOutByte
  void nrf24_writeReg(uint8_t cmd, uint8_t value) {
  void nrf24_writeRegs(uint8_t cmd, const uint8_t *buff, uint8_t size) {
  void nrf24_readRegs(uint8_t cmd, uint8_t *buff, uint8_t size) {
These functions include a small piece of assembler that calls the shiftOutByte
Can these small pieces of assembler be converted to C?
Not sure how easy that would be.?
I'm not at all familiar with assembler, but I think this translation would make the library more widely compatible

**Comment by dalxo** [comment]
I have a working fix at my setup and now it compiles. Try this:
1) In the header file nRF24L01.h wrap the code into the "extern C" block from this place (after pragma once:
![image](https://user-images.githubusercontent.com/5301406/148933871-05816e8f-51fc-4127-a1ff-0069a0a80f76.png)
2) At the end of the header file add closing bracket:
![image](https://user-images.githubusercontent.com/5301406/148934035-3a4ec920-a910-4c51-aa07-98fac193c80d.png)

3) Add a keyword "extern" to the definition of the shiftOutByte in the nRF24L01.c file:
"extern uint8_t shiftOutByte(uint8_t data) { ... }"
![image](https://user-images.githubusercontent.com/5301406/148934348-7d183a09-ac1c-40bb-825a-b427b393a486.png)

4) Disable LTO optimization in the Tools menu:
![image](https://user-images.githubusercontent.com/5301406/148934876-01ced1fc-4f7b-465d-951b-413f19468ee1.png)


It compiles and works on my Arduino IDE with DIY board manager.

Please, let me know if this fix works for you too. I will then update the repository and readme file. Thanks.

**Comment by dalxo** [comment]
"Can these small pieces of assembler be converted to C?"

Sure it does. In fact, everything was initially written in C but I didn't like the compiler's optimization work. If I recall, the compiled code was nearly 2x as big as now. It could still fit into the t13 flash but I found it as a waste. Therefore I converted it into my own assembler to further minimize the footprint.

**Comment by Nout1** [comment]
I've added the changes and now it compiles => great !
and even without LTO disabled it did compile .... but the size does not match your screenshot data?
Sketch below with LTO uses 384 bytes of program storage space + 6 bytes of dynamic memory
Sketch below without LTO 394 bytes of program storage space + 6 bytes of dynamic memory

What sketch did you use?
Do you use any other compiler settings?
I'm using Arduino IDE 1.8.19 now, so it should match your version

Sketch I've used:

#include "projdefs.h"
#include <nRF24L01.h>
void setup() { }
void loop() { }

Can you send me your sketch + did you use any other specific settings?

**Comment by dalxo** [comment]
If it compiles, I will update the repository. Thanks for opening this issue and letting me know. I will consider in the future how to directly support also Arduino IDE (besides native or Microchip Studio). 

The difference is in the setting of your project (check my screenshot to see what is left enabled and what is set). Arduino adds to the final image loads of other code (not only the nRF library) and features from the board manager - based on the settings. 

My test sketch:
#include "projdefs.h"
#include "nRF24L01.h"

#define CHANNEL 120

void setup() {
  // put your setup code here, to run once:
  nrf24_init();
}

void loop() {
  // put your main code here, to run repeatedly:
  nrf24_writeReg(W_REGISTER | RF_CH,    CHANNEL);
}

**Comment by Nout1** [comment]
There is still a problem.., something very strange....
When adding your library to my final project sketch, the code size suddenly reduces (which makes no sense)
And adding extra code lines using your library no longer changes anything on the compiled size (which makes no sense)
This is true in both cases with and without LTO enabled

I see no compiler errors, I made sure to exactly match all the setting from your screenshot; but still it seems like whatever I alter on my sketch, the compiled size is fixed; which again makes no sense...
Removing the library includes, all is normal again + code changes do translate in compiler file changes 
So still something is wrong
If I only include the projdefs.h files, already the complied size reduces, which makes no sense, it only includes definitions, and should not alter the code at all...
Very strange...

I will copy the projdefs file into the IDE, not using an include and see if that makes a difference

**Comment by Nout1** [comment]
I also tried your sketch and compiled result is very different
Sketch uses 474 bytes (46%) of program storage space. Maximum is 1024 bytes.
Global variables use 10 bytes (15%) of dynamic memory, leaving 54 bytes for local variables. Maximum is 64 bytes.
I

**Comment by Nout1** [comment]
The reported size of 474 bytes always repeats, even if I add extra lines to the sketch
I checked if another file with name projdefs.h exits on my computer, but it does not
I changed the name of the projdefs.h  file but it makes no difference
So given this strange behaviour I cannot yet confirm if it really compiles or not
Info: I'm working on a windows platform

**Comment by Nout1** [comment]
By adding all the library files into the sketch directly (so not using "include"), it compiles OK + the code size changes when changing the code. In this case I have to use LTO = enabled to see no error messages.

Testing the compiled code (no nRF connected, but AT25 + Tsensor and display are), it works fine
The total code size is 1080bytes, so just too big for AT13 => have used AT25 for now
Next steps is to validate if the nRF works
And next to check if I can further optimize the code to get it back into an AT13

Thanks for your help

I've to build a receiver now in order to see that the nRF transmitter works

**Comment by dalxo** [comment]
That's the reason why I use profesional tools (Microchip Studio) instead of Arduino IDE so I have a fine control of my compilation (unlike Arduino). What you describe is not anymore related to the library "as is" but the toolchain, IDE in use,  and compiler settings.  Note, that current projdefs.h is a sample related to the demo application and is not generic for *ANY* project (as is described in the readme file).

**Comment by dalxo** [comment]
For the sake of curiosity, I have imported my demo (transmitter) into the given Arduino IDE and it complies flawlessly. The sketch has code from main.c. (will flash it another time to verify it really works on the target chip) :
Sketch uses 498 bytes (48%) of program storage space. Maximum is 1024 bytes.
Global variables use 14 bytes (21%) of dynamic memory, leaving 50 bytes for local variables. Maximum is 64 bytes.

Anyway, this is still greater than what I get with pure C compiler in Microchip Studio :
Program Memory Usage 	:	378 bytes   36,9 % Full
Data Memory Usage 		:	6 bytes   9,4 % Full

I also tried to gradually add functions and see the Arduino's footprint and there was nothing strange. Each time I added into the sketch a new fcn from the library (which was not used before in the code), the footprint increased exactly by the size of the fcn + additional code to call it. I know the fcn size from disassembling the .o file to verify it was compiled and is identical. 

You have some strange compiler setting (assuming that you have plenty of board managers...) and something is simply not correctly set (or overwritten). 

What I find suspicious is that I have to disable LTO to get compilation done and you do not have to. That indicates having the same Arduino IDE version, you must have on your computer/IDE some additional stuff installed that messed up something.

**Comment by Nout1** [comment]
Above is good news, but bad news for me...
I did install Arduino 1.8.19 yesterday, but it reuses the actual libraries
I'll try  full reinstall, including setting up again the libraries

Another possible reason why Arduino fails on the #include could be related to not have converted the files into the required Arduino library format; which expects classes. Possibly under the hood some mixup occurs with another library?

But this all is no longer linked to your code, and I think I will be able to solve it by reinstalling all libs as well

Thanks a lot for your help !
and I've now learned how to fix such an issue.

My goal is to use your library for a set of sensors + one central receiver. 
One experiment is to time multiple a 4-digit 7-segment display with the nRF and share one data pin in order to save a pin on the ATTINY13 (after the nrf Trans/rec combination is working)

**Comment by dalxo** [comment]
Attached is my "quick&dirty" import of the demo for the Arduino IDE. It compiles both for transmitter and receiver (comment/uncomment relevant macro in projdefs.h). It is not yet verified in my testbed (will do it earliest tomorrow) so it is not 100% guarantee (only 99%). I plan later to make an "official clone" for Arduino but I have to test it first. The final footprint is 30% greater than what I get in Microchip IDE. 

My Arduino IDE setup: 1.8.19
Additional board manager (DIY): https://raw.githubusercontent.com/sleemanj/optiboot/master/dists/package_gogo_diy_attiny_index.json
Project config (as on my screenshot).

Please, go ahead and use it for your projects. If you can later write about them on Hackster.io (or elsewhere), let me know. 

I am glad you have learned something. As my very first boss used to say: "If things work on the first try, you have learnt nothing." Keep rolling and digging ;-)  I have in the pipeline on my Hackster.io blog a guide how to start developing ATtiny13a in Microchip Studio, let's see how much free time I will have to finish it.

[Demo_nrf24l01.zip](https://github.com/dalxo/nRF24L01_t13/files/7848959/Demo_nrf24l01.zip)

**Comment by Nout1** [comment]
I've downloaded the demo zip file + put all files in one directory and run it from there
In this case, the include works fine but I still needs LTO disabled to compile correctly

Your demo sketch now uses 516 bytes of program storage space. (you had 498 bytes)
Global variables it uses is 10 bytes. (you had 14 bytes)
Unclear why we have this small difference, but putting the files local, all works

I also added the includes back to my project + put all library files local => it compiles correctly
My sketch, with also sensor, display etc... now uses 1086 bytes, not too far from 1024

Do you still have the non-assembler version of your library code?
If yes, can you send it?
With LTO enabled, my code is clearly smaller and it might still compete in total memory usage compared to not being able to compile the library with LTO enabled

**Comment by Nout1** [comment]
The demo with transmitter and receiver in hardware is working
It's still on a breadboard, but it works.
I'll make it a PCB later
Next is to check if the multiplexing with a display can work

**Comment by dalxo** [comment]
Code from Arduino IDE works in my demo testbed too. I have already updated the main branch. 
Size: That's the same size as I have. My first import was only for transmitter (with reduced logic to support both TX/RX modes) so that's why the size was smaller. The Demo sketch I sent you has a little bit more code. 

Reducing 1086 down to 1024 means to get rid of 62 bytes, i.e. 31 average instructions. To give you some idea: 
Fcn call with 0 parameters == 2 bytes
Call with 1 param (8-bit argument) == 4 bytes
Call with 2 params (8-bit arguments) == 6 bytes

Avoid also if-then-else if you can. In my demo I toggle LED, so remove that code and you will already save 3x 2 bytes (1 asm instruction cbi/sbi is 2 bytes), i.e. 6 bytes.  Plus code to set pin direction (NRF24L01_DDR |= _BV(LED_PIN)), that could be cca 3 instructions (read reg, or with immediate arg, write reg) == 6 bytes. 

I do not have anymore (it was replaced) pure C-code to do a bit-banging for shiftOutByte. I do not think you will gain something doing in C. What LTO saves elsewhere, you will probably gain here, so it is a zero-sum game.

I will update readme and project description how to include it in Arduino IDE with DIY package manager. Will also try to fix the problem with LTO. I have one solution in mind - to put all functions with inline assembler into a separate assembler file (.S) and do not mix C/C++ with inline ASM.

Tips for PCB - don't forget to put a bypass cap to t13 (e.g. 100nF) to eliminate noise. Also, add at least 10us bypass on your nRF module (this drastically improves performance) - either on board next to the connector or solder it on nRF24 module directly. 

Good luck with the work!

**Comment by Nout1** [comment]
Good news!
The multiplexing works + I can get transmitter + receiver each fitting an ATTINY13.

In summary I now have a temperature sensor DS18B20 (one-wire) + a 7-segment display TM1637 (optional, is multiplexed and consumes only 1 GPIO instead of 2) + NRF24L01 + ATTINY13 combined that transmits the temperature (1004 bytes).
and a 2nd ATTINY13 + 7-segment display TM1637 + NRF24L01 + LED (optional, one GPIO was still available) as a receiver that displays the temperature. 
The receiver was for testing purposes only + will move from ATTINY into a D1 WEMOS to enable a connection to wifi.

So thanks again for the NRF library, example code, schematics and the great support you have given. It all has helped me a lot to realize my project!
![1642961737345](https://user-images.githubusercontent.com/13803887/150692566-40f448da-40f1-40f4-aa18-22b254e34467.jpg)
### ###

**Comment by dalxo** [comment]
That's really cool work what have you managed! Kudos!

I have played around and have a working solution with LDO enabled in Arduino IDE. The "troubled" functions with inline assembler are now in a separate asm file and a linker works flawlessly. Once all tests are done, I will commit it and you can try it - should yield less footprint than in pure C/C++. In my test demo in Arduino LTO enabled reduced the footprint by 20 bytes. Nothing spectacular but each byte matters in ATtiny13.

**Comment by Nout1** [comment]
Sounds good !

Thanks
Aarnout

Op ma 31 jan. 2022 09:54 schreef dalxo ***@***.***>:

**Comment by dalxo** [comment]
Tests passed successfully, the code is in the repository. Check it out. 
Enabling LTO you will reduce some footprint in the library (depends on which functions do you use, i.e. TX or RX) as well as in the rest of your project. 

I have further cut corners in the implementation to reduce the footprint. My RX demo (in C) is down by 14 bytes, TX is down by 6 bytes. I know, not dramatic but still something. 

I have some ideas to cut the code size. Will have a look at it and experiment when having some free time. 

Let me know if the code works for you and if there is a footprint reduction. 
Cheerz,
D.

**Comment by dalxo** [comment]
I tried some ideas to further reduce the code footprint and it downsized by 12 bytes (regardless RX or TX demo). Will run it in my test bed before commit. Should pass because it works in my other projects.

**Comment by Nout1** [comment]
Sounds good.
I'm on hold for a week on this waiting for PCB to arrive

Op zo 6 feb. 2022 19:23 schreef dalxo ***@***.***>:

**Comment by dalxo** [comment]
I have updated the repository. If you want to read about it and understand how the PROGMEM support works (could shave off more bytes), here is a short description: https://github.com/dalxo/nRF24L01_t13/blob/main/README.md#progmem-support

The demo is updated to work with the PROGMEM support.

**Comment by zesava** [comment]
> Good news! The multiplexing works + I can get transmitter + receiver each fitting an ATTINY13.
> 
> In summary I now have a temperature sensor DS18B20 (one-wire) + a 7-segment display TM1637 (optional, is multiplexed and consumes only 1 GPIO instead of 2) + NRF24L01 + ATTINY13 combined that transmits the temperature (1004 bytes). and a 2nd ATTINY13 + 7-segment display TM1637 + NRF24L01 + LED (optional, one GPIO was still available) as a receiver that displays the temperature. The receiver was for testing purposes only + will move from ATTINY into a D1 WEMOS to enable a connection to wifi.
> 
> So thanks again for the NRF library, example code, schematics and the great support you have given. It all has helped me a lot to realize my project! ![1642961737345](https://user-images.githubusercontent.com/13803887/150692566-40f448da-40f1-40f4-aa18-22b254e34467.jpg)

Hello.
Can you share your working Arduino code for transmitter ?
I plan to build a sensor node using Attiny84 + BME280 sensor
At the moment I have working setup similar to this
http://nerdralph.blogspot.com/2014/01/nrf24l01-control-with-3-attiny85-pins.html
But the main problem that this works only with fixed Vcc. when the voltage drops below some threshold it stops works. I need it to work with vcc in range 1,9-3.3V
