### ISSUE TITLE
possible code error, please check

### ISSUE THREAD

**Issue by Nout1** [dalxo/nRF24L01_t13#3]
In the demo project, function void testRecv(), I modified the message send from an uint8 into an uint16 + had to change the syntax for one line of code to make it work correctly for my application.
Can you check this is not general required to make the modification, and  if so adopt the library for it.

```
void testRecv() {
  union {
    uint8_t u8[NRF24_MAX_SIZE];
    uint32_t seqNum;
  } msg;

  uint32_t seqNumRx = 0;

  nrf24_writeReg(W_REGISTER | EN_AA,      NRF24_PIPE_0);  // en autoack
  nrf24_writeReg(W_REGISTER | NRF_STATUS, NRF24_STATUS_CLEAR_ALL);  // clear status
  
  // set RX mode, enable CRC with 2 bytes, mask all IRQs, power on nRF radio (POWER DOWN ==> STANDBY-1)
  nrf24_writeReg(W_REGISTER | NRF_CONFIG,
  NRF24_CFG_PWR_UP | NRF24_CFG_RX_MODE | NRF24_CFG_CRC_2B | NRF24_CFG_CRC_EN | NRF24_CFG_IRQ_MASK_ALL);
  
  _delay_ms(DELAY_POWER_UP_MILLIS); // there should be 5ms delay to bring nRF from the POWER DOWN to the POWER UP state (the worst case)
      
  while(1) {
    uint8_t status = nrf24_readReg(R_REGISTER | NRF_STATUS); // get status    
    // something received?
    if( status & NRF24_STATUS_RX_DR ) {
      // read everything what has been received from RX FIFO
      // (make sure you read everything from RX FIFO otherwise RX FIFO will overflow eventually)
      // (if you are lazy, you can always do FLUSH_RX after each read but you loose unprocessed frames, RX has 3 FIFOs)
      uint8_t msgSize = nrf24_readReg(R_RX_PL_WID); // read payload size
BOLD LINE: nrf24_readRegs(R_RX_PAYLOAD, msg.u8, msgSize);  // read payload into a buffer
      nrf24_writeReg(W_REGISTER | NRF_STATUS, NRF24_STATUS_CLEAR_ALL); // clear received flag
etc.....
```

The bold line I had to change into 
nrf24_readRegs(R_RX_PAYLOAD, (uint8_t*)&temp, msgSize);  // read payload into a buffer

temp is a uint16-t holding the temperature instead of the msg.u8 you have been using.
I needed to apply add (uint8_t*)& to the variable to point to its address and I'm reasonably sure this is always needed, but not present in your demo code.
Please check if this is correct.

Thanks

**Comment by dalxo** [comment]
I do not see any problem with my demo code. Could you please elaborate more in detail on why do you believe that "msg.u8" is not a pointer to an array of uint8_t as is required by the "nrf24_readRegs" function? 

The second argument of the nrf24_readRegs expects type "uint8_t*", i.e. pointer to uint8_t type, which is in C also a pointer to an array of elements with type uint8_t.

You try to pass totally different type as defined in the function signature (uint16_t), thus you have to re-type it - as you did. Now I don't understand what is the problem in my code?

**Comment by Nout1** [comment]
Ok, so the array variabele is already a pointer and consequently your code
is perfect as if is.
This closes the issue.

Thanks

Op ma 24 jan. 2022 13:30 schreef dalxo ***@***.***>:
